"""Generate docs/01-product-requirements/traceability.md (SRS §11.2 verification side).

Requirement IDs and attributes come from requirements-register.md (keyed to the authoritative SRS v0.1 and
approved/proposed change requests). Test links come from @pytest.mark.req(...) decorators, found with `ast`.

    uv run python scripts/trace.py   # rewrite the matrix; tests/test_traceability.py checks it is current
"""
import ast
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
REQ_DIR = ROOT.parent / "docs" / "01-product-requirements"
REGISTER = REQ_DIR / "requirements-register.md"
OUT = REQ_DIR / "traceability.md"
ID = r"(?:FR|DR|NFR|COM)-\d{2}"
ROW = re.compile(rf"^\| ({ID}) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|$", re.M)
NEEDS_TEST = ("Implemented", "Partial")


def requirements() -> list[dict]:
    return [dict(zip(["id", "summary", "source", "verify", "baseline", "status"], m.groups(), strict=True))
            for m in ROW.finditer(REGISTER.read_text(encoding="utf8"))]


def tagged_tests() -> dict[str, list[str]]:
    links: dict[str, list[str]] = {}
    for f in sorted((ROOT / "tests").glob("test_*.py")):
        for node in ast.walk(ast.parse(f.read_text(encoding="utf8"))):
            if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) or not node.name.startswith("test_"):
                continue
            for dec in node.decorator_list:
                if isinstance(dec, ast.Call) and ast.unparse(dec.func) == "pytest.mark.req":
                    for arg in dec.args:
                        links.setdefault(arg.value, []).append(f"`{f.name}::{node.name}`")
    return links


def problems(reqs: list[dict], links: dict[str, list[str]]) -> list[str]:
    known = {r["id"] for r in reqs}
    out = [f"{r['id']} is {r['status'].split()[0]} and verified by Test but has no tagged test"
           for r in reqs if "Test" in r["verify"] and r["status"].startswith(NEEDS_TEST) and r["id"] not in links]
    out += [f"tests tag unknown requirement {r}" for r in links if r not in known]
    return out


def render(reqs: list[dict], links: dict[str, list[str]]) -> str:
    def short(s: str) -> str:
        s = re.sub(r"\*\*|`", "", s)
        return s if len(s) <= 100 else s[:100] + "…"

    lines = ["# Traceability matrix (verification evidence)", "",
             "> [Docs index](../README.md) · [Register](requirements-register.md) · [Traceability](traceability.md) · "
             "[Change proposals](srs-change-proposal-CH-02.md) · [References](references.md)", "",
             "Generated by `backend/scripts/trace.py` from [requirements-register.md](requirements-register.md) and "
             "`@pytest.mark.req` tags. Do not edit by hand. Source evidence (EV-) links are in the SRS §11.2.", "",
             "| Requirement | Summary | Verify | Baseline | Implementation | Automated tests |", "|---|---|---|---|---|---|"]
    for r in reqs:
        tests = "<br>".join(links.get(r["id"], [])) or "—"
        lines.append(f"| {r['id']} | {short(r['summary'])} | {r['verify']} | {r['baseline']} | {r['status'].split(':')[0]} | {tests} |")
    return "\n".join(lines) + "\n"


def current(path: Path) -> str:
    return path.read_text(encoding="utf8").replace("\r\n", "\n") if path.exists() else ""


if __name__ == "__main__":
    reqs, links = requirements(), tagged_tests()
    OUT.write_text(render(reqs, links), encoding="utf8", newline="\n")
    print(f"wrote {OUT} ({len(reqs)} requirements)" + "".join(f"\n  ! {p}" for p in problems(reqs, links)))
