"""Generate docs/TRACEABILITY.md: SRS requirements -> tests that verify them (Sommerville §4.6 traceability).

Requirement IDs come from the tables in docs/SRS.md; test links come from @pytest.mark.req(...) tags.

    uv run python scripts/trace.py          # rewrite docs/TRACEABILITY.md
    uv run python scripts/trace.py --check  # exit 1 if out of date or a requirement is untraced (CI)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRS = ROOT.parent / "docs" / "SRS.md"
OUT = ROOT.parent / "docs" / "TRACEABILITY.md"
ROW = re.compile(r"^\| ((?:FR|NFR)-\d+) \| (.+?) \| (.+?) \| (Test|Inspection|Analysis|Demonstration) \|$", re.M)
TAG = re.compile(r"@pytest\.mark\.req\(([^)]*)\)\s*\n(?:@[^\n]*\n)*def (test_\w+)")


def requirements() -> list[tuple[str, str, str]]:
    return [(m[1], m[2], m[4]) for m in ROW.finditer(SRS.read_text(encoding="utf8"))]


def tagged_tests() -> dict[str, list[str]]:
    links: dict[str, list[str]] = {}
    for f in sorted((ROOT / "tests").glob("test_*.py")):
        for ids, name in TAG.findall(f.read_text(encoding="utf8")):
            for rid in re.findall(r"(?:FR|NFR)-\d+", ids):
                links.setdefault(rid, []).append(f"`{f.name}::{name}`")
    return links


def problems(reqs, links) -> list[str]:
    known = {r for r, _, _ in reqs}
    out = [f"{r} is verified by Test but has no tagged test" for r, _, v in reqs if v == "Test" and r not in links]
    out += [f"tests tag unknown requirement {r}" for r in links if r not in known]
    return out


def render(reqs, links) -> str:
    short = lambda s: re.sub(r"\*\*|`", "", s)[:110] + ("…" if len(s) > 110 else "")  # noqa: E731
    lines = ["# Traceability matrix", "",
             "Generated by `backend/scripts/trace.py` from [SRS.md](SRS.md) and `@pytest.mark.req` tags. Do not edit by hand.", "",
             "| Requirement | Summary | Verification | Verified by |", "|---|---|---|---|"]
    for rid, text, verif in reqs:
        lines.append(f"| {rid} | {short(text)} | {verif} | {'<br>'.join(links.get(rid, [])) or '—'} |")
    return "\n".join(lines) + "\n"


def main():
    reqs, links = requirements(), tagged_tests()
    text, issues = render(reqs, links), problems(reqs, links)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf8") != text:
            issues.append("docs/TRACEABILITY.md is out of date; run scripts/trace.py")
        print("\n".join(issues) or f"traceability OK: {len(reqs)} requirements")
        sys.exit(1 if issues else 0)
    OUT.write_text(text, encoding="utf8")
    print(f"wrote {OUT} ({len(reqs)} requirements)" + ("".join(f"\n  ! {i}" for i in issues)))


if __name__ == "__main__":
    main()
